version: '3'
services:
  web:
    container_name: web_app
    build:
      context: .
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./app:/var/www
    ports:
      - "8080:80"
    environment:
      ADMIN_UID: 9837452398563
  db:
    container_name: web_db
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: blargh
      MYSQL_DATABASE: valg
      MYSQL_USER: valg
      MYSQL_PASSWORD: secret
    volumes:
      - ./db:/docker-entrypoint-initdb.d:ro
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]